# Generated by Django 5.0.14 on 2026-06-21 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fecha_limite', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_ahorro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de Ahorro',
                'verbose_name_plural': 'Metas de Ahorro',
            },
        ),
    ]
