# Generated by Django 5.0.14 on 2026-06-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sena', '0002_metaahorro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('aprendiz', 'Aprendiz'), ('administrador', 'Administrador')], max_length=20),
        ),
    ]
